# Generated by Django 4.2 on 2025-08-16 15:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patronymic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('trader', 'Трейдер')], default='trader', max_length=20)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('in_consideration', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Размер депозита в KZT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль трейдера',
                'verbose_name_plural': 'Профили трейдеров',
            },
        ),
        migrations.CreateModel(
            name='TraderPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('card', 'Банковская карта'), ('crypto_wallet', 'Криптокошелек')], max_length=20, verbose_name='Тип реквизитов')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер карты')),
                ('card_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Держатель карты')),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес кошелька')),
                ('crypto_network', models.CharField(blank=True, max_length=50, null=True, verbose_name='Сеть (TRC20, ERC20 и т.д.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платежные реквизиты',
                'verbose_name_plural': 'Платежные реквизиты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=10, verbose_name='Тип заявки')),
                ('amount_usdt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество USDT')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс обмена')),
                ('amount_kzt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма в тенге')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('payment_method_type', models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('crypto_wallet', 'Криптокошелек')], max_length=20, null=True, verbose_name='Тип оплаты в сделке')),
                ('payment_bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Банк для оплаты')),
                ('payment_card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер карты для оплаты')),
                ('payment_card_holder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Держатель карты для оплаты')),
                ('payment_wallet_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес кошелька для оплаты')),
                ('payment_crypto_network', models.CharField(blank=True, max_length=50, null=True, verbose_name='Сеть для оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Комиссия трейдера')),
                ('assigned_trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный трейдер')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('used_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.traderpaymentmethod', verbose_name='Использованные реквизиты')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraderStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('orders_count', models.IntegerField(default=0, verbose_name='Количество заявок')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Заработано')),
                ('total_volume_usdt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Объем USDT')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статистика трейдера',
                'verbose_name_plural': 'Статистика трейдеров',
                'unique_together': {('trader', 'date')},
            },
        ),
    ]
