# Generated by Django 4.2 on 2025-08-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_bank_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_card_holder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_crypto_network',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_wallet_address',
        ),
        migrations.AddField(
            model_name='order',
            name='client_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Банк клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_card_holder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Держатель карты клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер карты клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_crypto_network',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сеть клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_payment_type',
            field=models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('crypto_wallet', 'Криптокошелек')], max_length=20, null=True, verbose_name='Тип оплаты клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес кошелька клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='trader_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Банк трейдера'),
        ),
        migrations.AddField(
            model_name='order',
            name='trader_card_holder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Держатель карты трейдера'),
        ),
        migrations.AddField(
            model_name='order',
            name='trader_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер карты трейдера'),
        ),
        migrations.AddField(
            model_name='order',
            name='trader_crypto_network',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сеть трейдера'),
        ),
        migrations.AddField(
            model_name='order',
            name='trader_payment_type',
            field=models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('crypto_wallet', 'Криптокошелек')], max_length=20, null=True, verbose_name='Тип оплаты трейдера'),
        ),
        migrations.AddField(
            model_name='order',
            name='trader_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес кошелька трейдера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='used_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.traderpaymentmethod', verbose_name='Использованные реквизиты трейдера'),
        ),
    ]
