# Generated by Django 4.2 on 2025-08-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_order_payment_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
