# Generated by Django 4.2 on 2026-06-26 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_supportmessage_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20, unique=True, verbose_name='Пара')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Курс')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс обмена',
                'verbose_name_plural': 'Курсы обмена',
            },
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('trader', 'Трейдер'), ('client', 'Клиент')], default='trader', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('card', 'Банковская карта'), ('crypto_wallet', 'Криптокошелек')], max_length=20, verbose_name='Тип реквизитов')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер карты')),
                ('card_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Держатель карты')),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес кошелька')),
                ('crypto_network', models.CharField(blank=True, max_length=50, null=True, verbose_name='Сеть')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реквизиты клиента',
                'verbose_name_plural': 'Реквизиты клиентов',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
