# Generated by Django 4.2 on 2026-06-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_client_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientPaymentMethod',
        ),
    ]
