# Generated by Django 4.2 on 2026-06-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_order_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ordermessage',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст сообщения'),
        ),
    ]
